import { ethers } from "ethers";
import { collection, getDocs } from "firebase/firestore";
import { db } from "@/lib/firebase";

export async function POST(req) {
  try {
    const { input } = await req.json();
    if (!input || typeof input !== "string") {
      return Response.json({ error: "Input kosong. Masukkan Tx Hash atau Wallet Address." }, { status: 400 });
    }

    const clean = input.trim().toLowerCase();
    const provider = new ethers.JsonRpcProvider(process.env.SEPOLIA_RPC_URL);

    let contractAddress = "0x5FbDB2315678afecb367f032d93F642f64180aa3";
    try {
      const fs = require("fs");
      const path = require("path");
      const contractConfig = JSON.parse(
        fs.readFileSync(path.join(process.cwd(), "contractAddress.json"), "utf8")
      );
      contractAddress = contractConfig.address?.toLowerCase() || contractAddress;
    } catch(e) {}

    const isTx = clean.startsWith("0x") && clean.length === 66;
    const isAddr = clean.startsWith("0x") && clean.length === 42;

    if (!isTx && !isAddr) {
      return Response.json({
        error: "Format tidak valid. Masukkan Tx Hash (0x…) 66 karakter atau Wallet Address (0x…) 42 karakter."
      }, { status: 400 });
    }

    const abi = ["function mintCredential(address to, string memory uri) public returns (uint256)"];
    const iface = new ethers.Interface(abi);

    const decodeMint = (calldata) => {
      try {
        const decoded = iface.decodeFunctionData("mintCredential", calldata);
        const b64 = decoded[1].replace("data:application/json;base64,", "");
        const meta = JSON.parse(Buffer.from(b64, "base64").toString("utf8"));
        return {
          userAddress: decoded[0].toLowerCase(),
          meta
        };
      } catch(e) { return null; }
    };

    // --- 1. Resolve input to a target transaction hash ---
    let targetTxHash = null;

    if (isTx) targetTxHash = clean;

    if (isAddr) {
      // Search contract event logs for mints to this address (fast)
      try {
        // ERC-721 Transfer(address _from, address _to, uint256 _tokenId) — mint emits Transfer from 0x0
        const mintSubject = ethers.id("Transfer(address,address,uint256)");
        const paddedTo = ethers.zeroPadValue(clean, 32);
        const filter = {
          address: contractAddress,
          topics: [mintSubject, null, paddedTo]
        };
        const blockNum = await provider.getBlockNumber();
        const logs = await provider.getLogs({
          ...filter,
          fromBlock: Math.max(0, blockNum - 500000),
          toBlock: blockNum
        });
        if (logs.length > 0) {
          // Latest minted credential
          targetTxHash = logs[logs.length - 1].transactionHash;
        } else {
          return Response.json({
            error: "Tidak ada sertifikat NeuroPath yang dicetak ke alamat ini dalam 500k blok terakhir."
          }, { status: 404 });
        }
      } catch (e) {
        return Response.json({
          error: "Pencarian log RPC gagal. Coba menggunakan Tx Hash langsung."
        }, { status: 502 });
      }
    }

    // --- 2. Fetch and validate transaction on-chain ---
    const tx = await provider.getTransaction(targetTxHash);
    const receipt = await provider.getTransactionReceipt(targetTxHash);

    if (!tx || !receipt) {
      return Response.json({ error: "Transaksi tidak ditemukan di jaringan Ethereum Sepolia." }, { status: 404 });
    }

    if (receipt.status !== 1) {
      return Response.json({ error: "Transaksi gagal (reverted) — tidak valid sebagai bukti." }, { status: 422 });
    }

    if (tx.to?.toLowerCase() !== contractAddress) {
      return Response.json({ error: "Transaksi tidak ditujukan ke kontrak NeuroPath." }, { status: 422 });
    }

    const mint = decodeMint(tx.data);
    if (!mint) {
      return Response.json({ error: "Data transaksi tidak menyerupai fungsi mintCredential." }, { status: 422 });
    }

    // --- 3. Cross-validate with our internal Firestore records (ensures it was generated by us) ---
    let internalMatch = null;
    try {
      const snap = await getDocs(collection(db, "users"));
      for (const userDoc of snap.docs) {
        const data = userDoc.data();
        const found = (data.credentials || []).find(c =>
          c.txHash?.toLowerCase() === targetTxHash
        );
        if (found) {
          internalMatch = {
            userId: userDoc.id,
            badgeType: found.badgeType,
            issuedAt: found.issuedAt,
            holderName: found.holderName || null,
            holderEmail: found.holderEmail || null,
            userName: data.name || null,
            userEmail: data.email || null,
            imageUri: found.imageUri || null
          };
          break;
        }
      }
    } catch(e) {}

    const archetype = mint.meta?.attributes?.find(a => a.trait_type === "Archetype")?.value || "Unknown";

    return Response.json({
      status: "verified",
      txHash: targetTxHash,
      explorerUrl: `https://sepolia.etherscan.io/tx/${targetTxHash}`,
      ownerAddress: mint.userAddress,
      archetype,
      holderName: internalMatch?.userName || internalMatch?.holderName || internalMatch?.userEmail || null,
      holderEmail: internalMatch?.userEmail || internalMatch?.holderEmail || null,
      imageUri: internalMatch?.imageUri || mint.meta?.image || null,
      network: "Ethereum Sepolia",
      contractAddress,
      issuedAt: internalMatch?.issuedAt || null,
      badgeType: internalMatch?.badgeType || "PROFILING_COMPLETE"
    }, { status: 200 });

  } catch (error) {
    console.error("Verify error:", error);
    return Response.json({ error: "Jaringan RPC sedang bermasalah. Coba lagi nanti." }, { status: 502 });
  }
}
