import { ethers } from "ethers";

export async function POST(req) {
  try {
    const { userId, badgeType, scores, userAddress, userEmail, userArchetype, userName } = await req.json();

    // Setup Provider and Signer (Ethereum Sepolia)
    const provider = new ethers.JsonRpcProvider(process.env.SEPOLIA_RPC_URL);
    const privateKey = process.env.PRIVATE_KEY;
    const wallet = new ethers.Wallet(privateKey, provider);

    // Read deployed contract address
    let contractAddress = "0x5FbDB2315678afecb367f032d93F642f64180aa3";
    try {
      const fs = require("fs");
      const path = require("path");
      const data = fs.readFileSync(path.join(process.cwd(), "contractAddress.json"), "utf8");
      contractAddress = JSON.parse(data).address;
    } catch(e) {
      console.log("Using default local contract address", contractAddress);
    }

    const abi = [
      "function mintCredential(address to, string memory uri) public returns (uint256)"
    ];
    const contract = new ethers.Contract(contractAddress, abi, wallet);

    const email = userEmail || "Anonymous";
    const archetype = userArchetype || "Unknown Archetype";

    // Create an elegant, minimalist SVG for the NFT image matching the NeuroPath aesthetic (Fully Minified)
    const svgImage = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 1000" width="800" height="1000"><rect width="100%" height="100%" fill="#0a0a0a"/><rect x="40" y="40" width="720" height="920" fill="none" stroke="#2a2a2a" stroke-width="1"/><rect x="55" y="55" width="690" height="890" fill="none" stroke="#1a1a1a" stroke-width="1"/><path d="M 400 100 L 400 140" stroke="#333333" stroke-width="1"/><text x="400" y="180" font-family="Georgia, serif" font-size="20" fill="#888888" text-anchor="middle" letter-spacing="6">NEUROPATH</text><text x="400" y="220" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif" font-size="12" fill="#555555" text-anchor="middle" letter-spacing="4">COGNITIVE CREDENTIAL</text><circle cx="400" cy="400" r="120" fill="none" stroke="#1a1a1a" stroke-width="1"/><circle cx="400" cy="400" r="100" fill="#111111" stroke="#222222" stroke-width="1"/><text x="400" y="430" font-family="Georgia, serif" font-size="90" fill="#ffffff" text-anchor="middle" font-weight="normal">N</text><text x="400" y="580" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif" font-size="14" fill="#666666" text-anchor="middle" letter-spacing="3">PRIMARY ARCHETYPE</text><text x="400" y="630" font-family="Georgia, serif" font-size="38" fill="#ffffff" text-anchor="middle" letter-spacing="2">${archetype.toUpperCase()}</text><line x1="250" y1="680" x2="550" y2="680" stroke="#1a1a1a" stroke-width="1"/><text x="400" y="740" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif" font-size="11" fill="#444444" text-anchor="middle" letter-spacing="2">AUTHENTICATED IDENTITY</text><text x="400" y="770" font-family="Courier New, monospace" font-size="14" fill="#aaaaaa" text-anchor="middle" letter-spacing="1">${email}</text><text x="400" y="800" font-family="Courier New, monospace" font-size="12" fill="#666666" text-anchor="middle">${userAddress}</text><path d="M 400 860 L 400 900" stroke="#333333" stroke-width="1"/><text x="400" y="930" font-family="-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif" font-size="10" fill="#333333" text-anchor="middle" letter-spacing="2">ISSUED ON ETHEREUM SEPOLIA</text></svg>`;

    const svgBase64 = Buffer.from(svgImage).toString("base64");
    const imageUri = "data:image/svg+xml;base64," + svgBase64;

    // Standard ERC-721 Metadata strictly adhering to OpenSea schema
    const certData = JSON.stringify({
      name: `NeuroPath: ${archetype}`,
      description: "A cryptographic proof of cognitive proficiency and archetype generated by NeuroPath.",
      image: imageUri,
      attributes: [
        { trait_type: "Archetype", value: archetype },
        { trait_type: "Owner", value: userAddress },
        { trait_type: "Holder", value: userName || email },
        { trait_type: "Platform", value: "NeuroPath" }
      ]
    });

    const metadataBase64 = Buffer.from(certData).toString("base64");
    const metadataUri = "data:application/json;base64," + metadataBase64;

    // 4. Send transaction
    const tx = await contract.mintCredential(userAddress, metadataUri);
    const receipt = await tx.wait();

    const credential = {
      txHash: receipt.hash,
      badgeType,
      issuedAt: new Date().toISOString(),
      network: "Ethereum Sepolia",
      contractAddress,
      ownerAddress: userAddress,
      holderName: userName || email,
      holderEmail: email,
      explorerUrl: `https://sepolia.etherscan.io/tx/${receipt.hash}`,
      imageUri: imageUri
    };

    return Response.json({
      txHash: receipt.hash,
      explorerUrl: credential.explorerUrl,
      certificateData: credential
    });
  } catch (error) {
    console.error("Mint error:", error);
    return Response.json({ error: "Failed to mint certificate" }, { status: 500 });
  }
}
